### PR TITLE
Modified etomo protocol to enhance usability of outputs downstream

### LINKED ISSUE #262: save alignment from etomo protocol output
to avoid running extra import protocol with xf files

### PR DESCRIPTION
**Pull request by rdrighetto**
The major changes are the following:

1) We now save the original tilt series (unbinned, non-interpolated) as an output, with the difference that it will have the associated transformation matrix determined in Etomo and excluded views taken into account, so downstream protocols (for example imod - apply transformation and imod - tomo reconstruction) will work correctly, including for the odd/even stacks if they are associated.
(a minor caveat is that this output TS is now possibly corrected for dead/hot pixels in the X-ray filtering procedure, the first step of Etomo. I think this is healthy, honestly).

2) Outputs are renamed for clarity: PrealignedTiltSeries, AlignedTiltSeries and TiltSeriesWithAli
TiltSeriesWithAli is the output I'm talking about in 1). Suggestions to enhance clarity are appreciated.

3) I explicitly enforce PrealignedTiltSeries, AlignedTiltSeries to not have odd/even associated, because they don't.

Albeit indirectly, this fixes #262.

### CODE REVIEW

**Review by azazellochg — APPROVED** [review]

**Comment by azazellochg** [comment]
If someone else could review it as well, it would be great!

**Review by pconesa — APPROVED** [review]
As I see it this is:

1.- Creating a right original tilt series with alignment (called TiltSeries)
2.- Old TiltSeries output is now named AlignedTiltseries and is the output of the fiducial alignment step? (So actually it was interpolated)

**Comment by rdrighetto** [comment]
Hi @pconesa - yes, that's exactly it

**Comment by azazellochg** [comment]
2 - yes, AlignedTS is the "final interpolated" one just before the reconstruction.

**Review by JorMaister — APPROVED** [review]

**Pull request merged**
