### PR TITLE
Jj bring az even odd

### PR DESCRIPTION
**Pull request by JorMaister**
All the refactorization and even / odd coded by @azazellochg and all the tests and changes derived from it and suggested by you are combined in this branch. All the tests pass.

### CODE REVIEW

**Comment by JorMaister** [comment]
To merge to devel when tomo 3.8.0 has been released

**Comment by azazellochg** [comment]
Hi @JorMaister I'm back and can review this by Sep 23rd. Is it ready to be checked?

**Comment by JorMaister** [comment]
Hi, @azazellochg. Indeed, I've been working on another branch that was created as a copy of this one and have finished adding and testing the excluded views functionality. I think I'll close this PR one and directly make a new PR containing all the changes at once.

**Comment by JorMaister** [comment]
Close this PR and open another one (including these changes and some the ones related to the excluded views management)

**Pull request closed without merging**
