### PR TITLE
Gs refactor

### LINKED ISSUE #281: check default values
1. https://github.com/scipion-em/scipion-em-imod/blob/f3efd176a9ca15d9c8b4a0c02e96bc4cd97ade8e/imod/protocols/protocol_xRaysEraser.py#L130

Defaults in SystemTemplate/cryoSample.adoc:

comparam.eraser.ccderaser.PeakCriterion = 8.0
comparam.eraser.ccderaser.DiffCriterion = 6.0

comparam.xcorr_pt.tiltxcorr.SizeOfPatchesXandY = 680,680
comparam.xcorr_pt.tiltxcorr.FilterRadius2 = 0.125
comparam.xcorr_pt.tiltxcorr.FilterSigma2 = 0.03

2. Fid model params in the track.com to be checked

### PR DESCRIPTION
**Pull request by azazellochg**
- move constants to a dedicated file
  - remove BETA status
  - fix default params (close #281 )
  - unify runProgram , use params dict
  - unify close outputs step
  - add possible outputs to all protocols
  - reduce number of get() queries
  - change several form params from Enum to Boolean, fix wrong default value types
  - do convert to float and normalize stacks in preXcorr
  - fix other newstack options tapering, antialias etc.
  - unify failed output set creation
  - unify oddEvenFlag
  - remove try/except decorator
  - refactor tests code
  - remove deprecated and unused code

Both workflow tests are passing. I also quickly went through a tutorial.
In the future PRs I can address odd/even stuff and then disabled views

### CODE REVIEW

**Comment by azazellochg** [comment]
I'm happy to answer any questions about the PR :)

**Comment by JorMaister** [comment]
Now I'm running the tests. One of them fails, with the following error message:

[   FAILED ] TestImodReconstructionWorkflow.test_excludeViewsOutputTS


Traceback (most recent call last):
  File "/home/jjimenez/anaconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/home/jjimenez/anaconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/jjimenez/anaconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/home/jjimenez/scipion3/scipion-em-imod/imod/tests/test_protocols_imod.py", line 308, in test_excludeViewsOutputTS
    self.assertEqual(tsOut.getSize(), self.excludeViewsOutputSizes[tsOut.getTsId()])
  File "/home/jjimenez/anaconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/home/jjimenez/anaconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 61 != 56

**Comment by azazellochg** [comment]
Ok, I'm checking this now

**Comment by azazellochg** [comment]
@JorMaister I realise I have modified the tests such that input TS are now BBa/BBb instead of a/b. So. the exclude views txt file needs to be updated

**Review by JorMaister — APPROVED** [review]

**Comment by Vilax** [comment]
This is a really good a big job

**Pull request merged**
