### PR TITLE
  - CTF correction: get rid of the decorator. Manage the failed TS in…

### PR DESCRIPTION
**Pull request by JorMaister**
… the createOutputStep.

  - Fix a bug in the base class for the generation of alignment files when there input TS are not aligned and there aren't excluded views.

### CODE REVIEW

**Review by pconesa — APPROVED** [review]

**Comment by azazellochg** [comment]
I've run TestImodCTFCorrectionWorkflow. The ctf correction protocol has 2 issues:

1. summary says WARNING! No CTFTomoSeries found for the tilt-series: []
2. output TS set remains open

**Comment by JorMaister** [comment]
Hi, @azazellochg,
The tests are passing in my machine. I've tried both branches devel and jj_update_tcl in scipion-em-tomo to try to reproduce it but without success. Could you attached the std.err and std.out?

**Comment by azazellochg** [comment]
[run.std.zip](https://github.com/user-attachments/files/15873828/run.std.zip)

**Comment by JorMaister** [comment]
My bad, @azazellochg, let me have a look at it.

**Comment by JorMaister** [comment]
I've been debugging what you found, @azazellochg. On the one hand, it was a bug in the generation of the summary message. But while doing that, I've observed that we were not writing correctly the defocus files in case of CTFs estimated using IMOD. We had this (the defocus file generated by IMOD is on the left and we were writing the defocus file on the right when reading the CTFTomoSeries from the sqlite in the convert input step of the next protocol, e. g., CTF correction):

image

It can be observed that the angle ranges were swapped and that the last column values were not indexed correctly. With the changeset added in the last push, they look like this:

image

The case shown correspond to IMOD flag = 0 (Plain estimation). I've followed the same logic for the rest of the cases: Astigmatism estimation, Phase-shift estimation, Astigmatism and phase shift estimation, and Astigmatism, phase shift and cut-on frequency estimation.

**Comment by azazellochg** [comment]
thank you for fixing this @JorMaister . I have never worked with ctf imod files and just trusted the existing code :)

**Review by azazellochg — APPROVED** [review]

**Review by Vilax — APPROVED** [review]

**Pull request merged**
